### ISSUE TITLE
允许指定代码块和轨道主题，匹配明暗变化

### ISSUE THREAD

**Issue by HowieHz** [HowieHz/halo-theme-higan-hz#37]
[upstream#111](https://github.com/guqing/halo-theme-higan/issues/111)

![image](https://github.com/HowieHz/halo-theme-higan-hz/assets/94725606/5af732da-e651-48cb-85b5-5cd19e783d0e)
![image](https://github.com/HowieHz/halo-theme-higan-hz/assets/94725606/17bb082d-d682-482c-be7f-37541e292c6d)

**Comment by HowieHz** [comment]
发现主题其实一直自己用着 tailwind 的
```css
* {
    scrollbar-color: color-mix(in oklch, currentColor 35%, transparent) transparent;
}
*:hover {
    scrollbar-color: color-mix(in oklch, currentColor 60%, transparent) transparent;
}
```
其实效果挺棒
