### ISSUE TITLE
首页和Archives页底部太空

### ISSUE THREAD

**Issue by Yorafa** [HowieHz/halo-theme-higan-hz#78]
如题，在没有底部样式，内容等的时候底部会特别空。有没有一种方法将后面的内容补充到前面？
如
![image](https://github.com/user-attachments/assets/613d4010-fd83-4b9d-bf3c-f2396841c733)

**Comment by HowieHz** [comment]
你好，意思是去除白圈的部分吗
![image](https://github.com/user-attachments/assets/b483fe50-4e16-4631-ae5c-f3bd44933230)

**Comment by Yorafa** [comment]
是的！能不能将后面一页内容补充到前面？要么就是把footer直接上提？

**Comment by HowieHz** [comment]
> 是的！能不能将后面一页内容补充到前面？要么就是把footer直接上提？

可以，我将很快做出一个新配置项用于配置此项。
我说怪不得这么眼熟，之前是作为 bug 修掉了。

https://github.com/HowieHz/halo-theme-higan-hz/issues/60
https://github.com/HowieHz/halo-theme-higan-hz/compare/v1.6.0...v1.6.1

**Comment by Yorafa** [comment]
另外有个小疑问, 为什么使用select来设置sns的资料？自己填写不会好一些吗？如:
```yaml
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: repeater
          name: index_sns
          label: 首页社交资料展示
          value: []
          children:
            - $formkit: text
              name: url
              label: URL链接
              validation: "required"
              placeholder: "请输入你要展示的社交资料的 URL 链接"
            - $formkit: text
              name: icon
              label: 图标名称
              validation: "required"
              placeholder: "例如： simple-icons:github"
            - $formkit: text
              name: aria_label
              label: 图标提示
              placeholder: "请输入你要展示的社交资料的提示"
```
