### ISSUE TITLE
首页联系方式选择支持完全自定义

### ISSUE THREAD

**Issue by HowieHz** [HowieHz/halo-theme-higan-hz#83]
```yaml
    - group: sns
      label: 社交资料
      formSchema:
        - $formkit: repeater
          name: index_sns
          label: 首页社交资料展示
          value: []
          children:
            - $formkit: text
              name: url
              label: URL链接
              validation: "required"
              placeholder: "请输入你要展示的社交资料的 URL 链接"
            - $formkit: text
              name: icon
              label: 图标名称
              validation: "required"
              placeholder: "例如： simple-icons:github"
            - $formkit: text
              name: aria_label
              label: 图标提示
              placeholder: "请输入你要展示的社交资料的提示"
```
from @Yorafa
